### ISSUE TITLE
PNG/TGA texture support

### ISSUE THREAD

**Issue by VinnyVicious** [IgeNiaI/Q-Zandronum#249]
Does the engine allow for high-resolution textures and sprites? Where should the files be placed for them to be taken into account by engine? Is there a guide to replace existing weapon sprites with high-resolution PNGs?

**Comment by IgeNiaI** [comment]
Q-Zandronum has same support for high-resolution PNGs as vanilla Zandronum. What you need to do is to implement everything using low resolution sprites so that the engine would know the weapon/monster size, and then add the high resolution images into a `HIRES` folder in your mod
Take a look how the Unreal Tournament weapons for QC:DE addon does that: https://www.moddb.com/mods/quake-champions-doom-edition/addons/unreal-tournament-weapons-for-q-zandronum
