### ISSUE TITLE
Q-Zandronum won’t play MIDI music due to a missing library

### ISSUE THREAD

**Issue by yum13241** [IgeNiaI/Q-Zandronum#318]
this is the error.

`Could not load libfluidsynth.so.1: libfluidsynth.so.1: cannot open shared object file: No such file or directory`

`Could not open MIDI out device`

I do have fluidsynth installed. Trying to look up the .so.1 file just gets me a bunch of fedora links and other stuff that won't work.\

fluidsynth seems to provide the following libs:

usr/lib/libfluidsynth.so
usr/lib/libfluidsynth.so.3
usr/lib/libfluidsynth.so.3.1.1
but not libfluidsynth.so.1

I'm on EndeavorOS btw, which is for all intents and purposes Arch. I'm using the ELF binary on your website, not the AUR package that would take me eons to compile.

**Comment by user12309** [comment]
The problem is that q-zandronum inherited the old zandronum sound code that was intended to work with now discontinued fluidsynth version 1.x. So any linux distribution that doesn't have the old fluidsynth will encounter this problem. You may read more about it from GZDoom dev response: https://www.doomworld.com/forum/topic/130780-getting-fluidsynth-to-work-on-linux-zandronum-ubuntu-based/

Fluidsynth should be optional dependency and maybe swapping it with timidity will do the trick, but I need to check it myself to be sure.

**Comment by yum13241** [comment]
I wish (q-)zandronum just used smth like zmusic lol

**Comment by IgeNiaI** [comment]
Sorry I didn't respond earlier, I was away from home all this time.
Honestly I don't think I will fix this myself. Q-Zandronum was intended as a gameplay upgrade to vanilla Zandronum and I am not going to modify sound system as well.
So, this will only be fixed if vanilla Zandronum fixes it first.
